### ISSUE TITLE
No longer working with Flogger

### ISSUE THREAD

**Issue by mmnaseri** [agsimeonov/flogger-fluentd-backend#1]
Hi!

I am trying to use this against flogger 0.5.1 and this no longer seems to work due to some internal Flogger API changes:

```
java.lang.NoSuchMethodException: com.google.common.flogger.backend.system.DefaultPlatform.resolveAttribute(java.lang.String,java.lang.Class)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2633)
	at com.agsimeonov.flogger.backend.fluentd.FluentdBackendFactory.resolveAttribute(FluentdBackendFactory.java:116)
	at com.agsimeonov.flogger.backend.fluentd.FluentdBackendFactory.create(FluentdBackendFactory.java:89)
	at com.google.common.flogger.backend.system.DefaultPlatform.getBackendImpl(DefaultPlatform.java:89)
	at com.google.common.flogger.backend.Platform.getBackend(Platform.java:175)
	at com.google.common.flogger.FluentLogger.forEnclosingClass(FluentLogger.java:71)
```

**Comment by agsimeonov** [comment]
Hi @mmnaseri thanks for reporting this. I will try and take a look this coming week and hopefully I can resolve it.

**Comment by mmnaseri** [comment]
Cool. Thanks for looking into it. I tried to clone your repo and run the tests, but some of the tests had compile errors with `0.4`. May be something wrong with my setup?
